In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6,7,12])

array([ 2,  3,  4,  5,  6,  7, 12])

In [3]:
x = [1,2,4,6,3,2,6,7,'hello','hey']

In [4]:
np.array(x)

array(['1', '2', '4', '6', '3', '2', '6', '7', 'hello', 'hey'],
      dtype='<U11')

In [5]:
x = [1,2,4,6,3,2,6,7,True,False]

In [6]:
np.array(x)

array([1, 2, 4, 6, 3, 2, 6, 7, 1, 0])

In [7]:
x = [1,2,4,6,3,2,6,7,True,False,12.34,33.33]

In [8]:
np.array(x)

array([ 1.  ,  2.  ,  4.  ,  6.  ,  3.  ,  2.  ,  6.  ,  7.  ,  1.  ,
        0.  , 12.34, 33.33])

In [9]:
x = [1,2,4,6,3,2,6,7,True,False,12.34,33.33,'hello','bye']

In [10]:
np.array(x)

array(['1', '2', '4', '6', '3', '2', '6', '7', 'True', 'False', '12.34',
       '33.33', 'hello', 'bye'], dtype='<U32')

In [11]:
import sys

In [12]:
sys.getsizeof(list())

64

In [13]:
sys.getsizeof(np.array([]))

96

In [14]:
sys.getsizeof(0)

24

In [15]:
sys.getsizeof(1)

28

In [22]:
sys.getsizeof([1,2,4,5,6])

104

In [28]:
x = list(range(10000))

In [29]:
# x

In [30]:
xx = np.array(x)

In [31]:
sys.getsizeof(x)

90112

In [32]:
sys.getsizeof(xx)

40096