In [1]:
# https://www.numpy.org/devdocs/user/quickstart.html
import numpy as np

In [2]:
x = [2,3,5,6,'hi','hello',10.5]

In [3]:
x

[2, 3, 5, 6, 'hi', 'hello', 10.5]

In [5]:
np.array([2,4,6,7,3,5,6,7.5])

array([2. , 4. , 6. , 7. , 3. , 5. , 6. , 7.5])

In [6]:
np.array([4,5,6,3,3,'hi',6.7,44.5])

array(['4', '5', '6', '3', '3', 'hi', '6.7', '44.5'], dtype='<U11')

In [7]:
np.array([2,4,6,6,True])

array([2, 4, 6, 6, 1])

# Ways to create array

In [8]:
# first method
x = np.array([4,6,8,8,6,8,2,12,56,8])

In [9]:
print(x)

[ 4  6  8  8  6  8  2 12 56  8]


In [10]:
x[0]

4

In [11]:
x[-1]

8

In [12]:
x[0:4]

array([4, 6, 8, 8])

In [13]:
# second method
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [14]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
# third method
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# fourth method
# np.linspace(5,20)
# np.linspace(start=5,stop=20,num=10)
np.linspace(start=5,stop=20,num=10,retstep=True)

(array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
        13.33333333, 15.        , 16.66666667, 18.33333333, 20.        ]),
 1.6666666666666667)

In [24]:
# fifth method
np.random.random()

0.5419666790654963

In [26]:
np.random.random((2,5))

array([[0.40113204, 0.53183328, 0.56908228, 0.2260657 , 0.09449009],
       [0.48234037, 0.23053026, 0.66954753, 0.98298419, 0.66096295]])

In [29]:
np.random.randn(4,4)

array([[-1.09099558,  1.54971284, -0.99472288,  2.323899  ],
       [-0.51935278,  0.75416939,  1.28933919, -0.10221746],
       [-0.60357576, -0.10635731, -0.2342562 ,  0.04652731],
       [ 0.77902378, -1.91775214,  0.36269642,  0.24959155]])

In [33]:
np.random.randint(10)

2

In [34]:
np.random.randint(10,50)

34

In [35]:
# will return 20 random numbers in range of 10 an 100
np.random.randint(10,100,20)

array([82, 48, 49, 79, 74, 83, 71, 99, 53, 81, 48, 10, 50, 35, 75, 37, 50,
       76, 59, 72])

# Slicing of Numpy Arrays

In [36]:
x = np.random.randint(10,100,20)

In [37]:
x

array([13, 92, 58, 20, 78, 85, 29, 34, 10, 88, 24, 24, 83, 93, 63, 75, 22,
       34, 44, 40])

In [38]:
x[0:6]

array([13, 92, 58, 20, 78, 85])

In [39]:
x[10:-1]

array([24, 24, 83, 93, 63, 75, 22, 34, 44])

In [41]:
# x[index(lowerbound) : position(upperbound) : step(default=1)]
x[10:0:-1]

array([24, 88, 10, 34, 29, 85, 78, 20, 58, 92])

In [42]:
x[-1:-10:-1]

array([40, 44, 34, 22, 75, 63, 93, 83, 24])

In [43]:
x[-10:-1]

array([24, 24, 83, 93, 63, 75, 22, 34, 44])

In [44]:
x = np.array([[5,7,3,5],[8,7,9,3],[3,6,8,2],[4,6,3,7],[7,8,3,4]])

In [45]:
x

array([[5, 7, 3, 5],
       [8, 7, 9, 3],
       [3, 6, 8, 2],
       [4, 6, 3, 7],
       [7, 8, 3, 4]])

In [46]:
x[0]

array([5, 7, 3, 5])

In [47]:
x[0][0]

5

In [48]:
x[0:2]

array([[5, 7, 3, 5],
       [8, 7, 9, 3]])

In [52]:
x[0:5,0:2]

array([[5, 7],
       [8, 7],
       [3, 6],
       [4, 6],
       [7, 8]])

In [53]:
x[0:2,0:2]

array([[5, 7],
       [8, 7]])

In [ ]:
# x.shape

In [55]:
x.reshape(4,5)

array([[5, 7, 3, 5, 8],
       [7, 9, 3, 3, 6],
       [8, 2, 4, 6, 3],
       [7, 7, 8, 3, 4]])

In [60]:
x.T

array([[5, 8, 3, 4, 7],
       [7, 7, 6, 6, 8],
       [3, 9, 8, 3, 3],
       [5, 3, 2, 7, 4]])

# Numpy Methods

In [69]:
np.random.seed(6)
np.random.randint(10,100)

20

In [70]:
x = np.random.randint(10,100,20)

In [71]:
x

array([83, 94, 89, 90, 72, 35, 11, 85, 87, 67, 36, 43, 78, 43, 18, 12, 86,
       94, 41, 76])

In [72]:
x.min()

11

In [73]:
x.max()

94

In [74]:
x.mean()

62.0

In [75]:
x.argmax()

1

In [76]:
x.argmin()

6

In [77]:
x.argsort()

array([ 6, 15, 14,  5, 10, 18, 13, 11,  9,  4, 19, 12,  0,  7, 16,  8,  2,
        3,  1, 17], dtype=int64)